### ISSUE TITLE
occurence of text hard to use

### ISSUE THREAD

**Issue by starmindfr** [cyb3rdog/Cyb3rVector#12] opened 2022-01-07 11:48 UTC
hello not sure if issue is a bug or difficult to use issue, i tried to use the sample "clock" to say word "clock" and get the 3 sentences, but this never works, i trieds others words, even with count > 2 and saying 3 times "clock" it still connecting to internet to give me definition of "clock". Others samples that donc look for a voice text part after hey victor run fine, event adding a text to read before to check "clock" i get the text, but obviously vector will not understand or compare texts . i have the latest release 1.8 on vector, a valid subscription enabled  and no escape pod.

Thanks again for this great application

**Comment by cyb3rdog** [comment] 2022-01-07 20:46
Hi,
thanks a lot for your appreciation and for your interest in this project.

- First of all, Vector's latest production software (1.8) can currently recognize and process only about 42 known voice commands (see the [default_intents.json](https://github.com/cyb3rdog/Cyb3rVector/blob/Resources/default_intents.json) file). These are the only "intents" / voice commands which are sent over to the SDK and to clients like Cyb3rVector/CodeLab.
- Currently, the only way how to enable Vector to process new, own, custom voice commands is only with EscapePod and/or OSKR (you can learn more about the diferences between them [here in discussions](https://github.com/cyb3rdog/Cyb3rVector/discussions/6) section)
- All other voice interaction with Vector is handled by DDL servers with so called 'Knowledge Graph', where the voice command is sent to DDL server's and returns back to Vector, with something for him to say. This unfortunatelly is not passed further on, to the Vector's SDK and therefore no client applications, including the Cyb3rVector and CodeLab cannot react to it. Hopefuly, we will see a software update for Vector soon, where this will be more open ....

So long story short, if you will tell vector a Voice command, and you will see Vector react with the "Internet"= 'knowledge graph' = the "I have a question" animation, no client application including CodeLab will be able to react to this, because it is simply not sent to it...
You actually can use the "WakeWordEnd" or "UserIntent" events as a first blocks and then attach the "DisplayText" to see on Vectors screen, what Voice commands were actually passed by Vector to to the client application, and which not.

In regards to the "clock" example, let me explain how it works:
![image](https://user-images.githubusercontent.com/12493945/148604592-fba2fcb9-e001-49be-acaf-c646f6cd2133.png)
- The first block "WakeWordEnd" is an event, which only reacts to recognized voice commans (the 42 mentioned commands).
- When you say "Hey Vector, what time is it?", or "what's the time" the intent "show_clock" will be sent by Vector to the application for further processing.
- If the next "IF" block finds the text "clock" in the "show clock" intent, it will continue with making Vector say a thing correspondingly to the actual time.

Hope this will help you.

**Comment by cyb3rdog** [comment] 2022-01-07 20:47
Closing, as its not a bug nor an issue of Cyb3rVector/Codelab.
Described limitation is in the Vector's software.

**Closed as completed by cyb3rdog** 2022-01-07 20:47 UTC
